//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chinmaya.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CM_Users
    {
        public System.Guid UserGUID { get; set; }
        public System.Guid CenterGUID { get; set; }
        public Nullable<System.Guid> RoleGUID { get; set; }
        public Nullable<System.Guid> CityGUID { get; set; }
        public Nullable<System.Guid> StateGUID { get; set; }
        public Nullable<System.Guid> CountryGUID { get; set; }
        public Nullable<System.Guid> AgeGroupGUID { get; set; }
        public Nullable<System.Guid> GenderGUID { get; set; }
        public string Email { get; set; }
        public Nullable<bool> EmailConfirmed { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string Address { get; set; }
        public string ZipCode { get; set; }
        public string HomePhone { get; set; }
        public string CellPhone { get; set; }
        public string EmergencyPhone { get; set; }
        public string PhotographLocation { get; set; }
        public Nullable<bool> IsIndividual { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<bool> IsApproveMailSent { get; set; }
        public Nullable<bool> IsLocked { get; set; }
        public Nullable<int> NumberOfAttempts { get; set; }
        public string Comments { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string CreateUser { get; set; }
        public string UpdatedUser { get; set; }
        public bool Active { get; set; }
    
        public virtual CM_Centers CM_Centers { get; set; }
    }
}
